"""all tables

Revision ID: 0a0a3e8e3c2b
Revises: 0f4fbef48472
Create Date: 2024-04-10 16:11:52.403620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a0a3e8e3c2b'
down_revision: Union[str, None] = '0f4fbef48472'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('receiver_account', sa.Integer(), nullable=True),
    sa.Column('accountholder_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accountholder_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('TrasactionDataDaily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_transaction_month', sa.String(), nullable=False),
    sa.Column('day_transaction_year', sa.String(), nullable=False),
    sa.Column('day_total_transactions', sa.String(), nullable=False),
    sa.Column('day_total_deposit', sa.String(), nullable=False),
    sa.Column('day_total_withdraw', sa.String(), nullable=False),
    sa.Column('day_total_transferred', sa.String(), nullable=False),
    sa.Column('day_total_received', sa.String(), nullable=False),
    sa.Column('day_transaction_day', sa.String(), nullable=False),
    sa.Column('day_mab', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accountholder_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accountholder_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('TrasactionDataMonthly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_month', sa.String(), nullable=False),
    sa.Column('transaction_year', sa.String(), nullable=False),
    sa.Column('total_transactions', sa.String(), nullable=False),
    sa.Column('total_deposit', sa.String(), nullable=False),
    sa.Column('total_withdraw', sa.String(), nullable=False),
    sa.Column('total_transferred', sa.String(), nullable=False),
    sa.Column('total_received', sa.String(), nullable=False),
    sa.Column('mab', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accountholder_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accountholder_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('pan_number', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('accountholder_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accountholder_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number'),
    sa.UniqueConstraint('pan_number')
    )
    op.add_column('user', sa.Column('password', sa.String(), nullable=False))
    op.add_column('user', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user', sa.Column('phone_number', sa.String(), nullable=False))
    op.add_column('user', sa.Column('otp', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'user', ['otp'])
    op.create_unique_constraint(None, 'user', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'otp')
    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'password')
    op.drop_table('account')
    op.drop_table('TrasactionDataMonthly')
    op.drop_table('TrasactionDataDaily')
    op.drop_table('Transaction')
    # ### end Alembic commands ###
